version: '3.1'

services:

  yourls:
    image: yourls:latest
    container_name: yourls
    restart: unless-stopped
    ports:
      - 8080:80
    expose:
      - 80
    environment:
      YOURLS_SITE: http://localhost:8080 # please adjust to your domain
      YOURLS_USER: admin # please adjust
      YOURLS_PASS: admin # please adjust
      YOURLS_DB_HOST: mysql
      YOURLS_DB_USER: yourls
      YOURLS_DB_NAME: yourls
      YOURLS_DB_PASS: yourls # please adjust
    volumes:
      - ./security.conf:/etc/apache2/conf-enabled/security.conf:ro      

  mysql:
    image: mysql:latest
    container_name: yourls-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yourls
      MYSQL_USER: yourls
      MYSQL_PASSWORD: yourls # please adjust
      MYSQL_ROOT_PASSWORD: yourls # please adjust
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: